name: Testing for pull_request to a release branch

on:
  pull_request:
    branches:
      - 'release/**'

jobs:
  mock_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' #install the python needed
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ci/bin/requirements.txt
    - name: Mock test
      run: |
        cd ci/mock_test
        ./run_ci.sh
